name: Deploy CloudFormation EC2

on:
  workflow_dispatch:
    inputs:
      instance_type:
        description: 'Choose an EC2 Instance Type'
        required: true
        default: 't2.micro'
        type: choice
        options:
          - t2.micro
          - t2.small
          - t2.medium

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::084828603933:role/GitHubActionsRole03
          role-session-name: GitHubActionsSession
          aws-region: us-east-1
      
      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ec2-instance.yml \
            --stack-name GitHubActionsCloudStack01 \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides InstanceType=${{ github.event.inputs.instance_type }}